Forensystem/routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\BoardController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\TopicController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

















// Public

Route::view('/','components.login-form')->name('loginPage');
Route::post('/login', [AuthController::class,'login'])->name('login');
Route::view('/registerForm','components.register')->name('registerForm');
Route::view('/resetPasswordForm','components.forget-password')->name('resetPasswordForm');
Route::post('/usersRegister',[AuthController::class,'register'])->name('register');
Route::post('/sendResetMail',[AuthController::class,'sendResetMail'])->name('reset.mail');
Route::post('/verifyResetCode',[AuthController::class,'verifyResetCode'])->name('verifyCode');
Route::post('/resetPassword',[AuthController::class,'resetPassword'])->name('reset.password');
Route::get('/getBoardTopics/{board}',[TopicController::class,'boardTopics'])->name('board.topics');
Route::post('/search',[TopicController::class,'search'])->name('search');
Route::view('getForgetPassword','components.forget-password')->name('test');


// Authentication
Route::middleware('auth')->group(function (){
    Route::resource('notification', NotificationController::class);
    Route::get('/notificationOp/{op}',[NotificationController::class,'readOrDelete'])->name('notification.options');

    Route::get('/getProfilePage',[AuthController::class,'getProfilePage'])->name('get.Account');
    Route::put('/editProfile',[AuthController::class,'editAccount'])->name('edit.Account');

    Route::get('logout',[AuthController::class,'logout'])->name('logout');

    Route::resource('comment',CommentController::class);
    Route::resource('topic', TopicController::class)->except('index','show');

    Route::middleware('can:isAdmin')->group(function (){
        Route::resource('board', BoardController::class);
        Route::resource('users', UsersController::class);
    });
});

Route::resource('topic', TopicController::class)->only('index','show');

Forensystem/resources/views/management/boards.blade.php
@extends('layout.main')
@section('body')


    <x-messages-form/>

    <div class="d-flex justify-content-around">

        <form action="{{ route('board.store')}} " method="post" class="mx-2">
            @csrf
            <div class="input-group mb-3 my-3">
                    <button class="btn btn-success" type="submit" id="button-addon1">Add</button>
                    <input name="name" type="text" class="form-control"
                           placeholder="Board Name" aria-label="Example text with button addon"
                           aria-describedby="button-addon1">
            </div>
        </form>

        @if(isset($boardToEdit))
            <form action="{{ route('board.update',$boardToEdit->id)}} " method="post" class="mx-2">
                @csrf
                @method('PUT')
                <div class="input-group mb-3 my-3">
                    <button class="btn btn-warning" type="submit" id="button-addon1">Edit</button>
                    <input name="name" type="text" class="form-control"
                           placeholder="Board Name" aria-label="Example text with button addon"
                           aria-describedby="button-addon1" value="{{$boardToEdit->name}}">
                </div>
            </form>
        @endif

    </div>

    <div class="container text-center">
            <div class="row">
                @foreach($boards as $board)
                    <x-board-box :board="$board" />
                @endforeach
            </div>
    </div>

    <div class="d-flex justify-content-center my-3">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item"><a class="page-link" href="{{$boards->previousPageUrl()}}">Previous</a></li>
                <li class="page-item"><a class="page-link" href="{{$boards->nextPageUrl()}}">Next</a></li>
            </ul>
        </nav>
    </div>
@endsection

Forensystem/resources/views/management/users.blade.php
@extends('layout.main')
@section('body')

    <x-messages-form/>

    <div class="container my-3">
        <div class="col-md-9 col-md-pull-3">
            @foreach($users as $user)
                <x-user-layout :$user />
            @endforeach
        </div>
    </div>


    <div class="d-flex justify-content-center my-3">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item"><a class="page-link" href="{{$users->previousPageUrl()}}">Previous</a></li>
                <li class="page-item"><a class="page-link" href="{{$users->nextPageUrl()}}">Next</a></li>
            </ul>
        </nav>
    </div>

@endsection


<style>
    body {
        margin-top: 20px;
        background-color: #eee;
    }

    .search-result-categories > li > a {
        color: #b6b6b6;
        font-weight: 400
    }

    .search-result-categories > li > a:hover {
        background-color: #ddd;
        color: #555
    }

    .search-result-categories > li > a > .glyphicon {
        margin-right: 5px
    }

    .search-result-categories > li > a > .badge {
        float: right
    }

    .search-results-count {
        margin-top: 10px
    }

    .search-result-item {
        padding: 20px;
        background-color: #fff;
        border-radius: 4px
    }

    .search-result-item:after,
    .search-result-item:before {
        content: " ";
        display: table
    }

    .search-result-item:after {
        clear: both
    }

    .search-result-item .image-link {
        display: block;
        overflow: hidden;
        border-top-left-radius: 4px;
        border-bottom-left-radius: 4px
    }

    @media (min-width: 768px) {
        .search-result-item .image-link {
            display: inline-block;
            margin: -20px 0 -20px -20px;
            float: left;
            width: 200px
        }
    }

    @media (max-width: 767px) {
        .search-result-item .image-link {
            max-height: 200px
        }
    }

    .search-result-item .image {
        max-width: 100%
    }

    .search-result-item .info {
        margin-top: 2px;
        font-size: 12px;
        color: #999
    }

    .search-result-item .description {
        font-size: 13px
    }

    .search-result-item + .search-result-item {
        margin-top: 20px
    }

    @media (min-width: 768px) {
        .search-result-item-body {
            margin-left: 200px
        }
    }

    .search-result-item-heading {
        font-weight: 400
    }

    .search-result-item-heading > a {
        color: #555
    }

    @media (min-width: 768px) {
        .search-result-item-heading {
            margin: 0
        }
    }
</style>