Forensystem/routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\BoardController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\TopicController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

















// Public

Route::view('/','components.login-form')->name('loginPage');
Route::post('/login', [AuthController::class,'login'])->name('login');
Route::view('/registerForm','components.register')->name('registerForm');
Route::view('/resetPasswordForm','components.forget-password')->name('resetPasswordForm');
Route::post('/usersRegister',[AuthController::class,'register'])->name('register');
Route::post('/sendResetMail',[AuthController::class,'sendResetMail'])->name('reset.mail');
Route::post('/verifyResetCode',[AuthController::class,'verifyResetCode'])->name('verifyCode');
Route::post('/resetPassword',[AuthController::class,'resetPassword'])->name('reset.password');
Route::get('/getBoardTopics/{board}',[TopicController::class,'boardTopics'])->name('board.topics');
Route::post('/search',[TopicController::class,'search'])->name('search');
Route::view('getForgetPassword','components.forget-password')->name('test');


// Authentication
Route::middleware('auth')->group(function (){
    Route::resource('notification', NotificationController::class);
    Route::get('/notificationOp/{op}',[NotificationController::class,'readOrDelete'])->name('notification.options');

    Route::get('/getProfilePage',[AuthController::class,'getProfilePage'])->name('get.Account');
    Route::put('/editProfile',[AuthController::class,'editAccount'])->name('edit.Account');

    Route::get('logout',[AuthController::class,'logout'])->name('logout');

    Route::resource('comment',CommentController::class);
    Route::resource('topic', TopicController::class)->except('index','show');

    Route::middleware('can:isAdmin')->group(function (){
        Route::resource('board', BoardController::class);
        Route::resource('users', UsersController::class);
    });
});

Route::resource('topic', TopicController::class)->only('index','show');

Forensystem/resources/views/main/dashboard.blade.php
@php use Illuminate\Support\Collection; @endphp
@extends('layout.main')
@section('body')

    <div class="container">
        <x-messages-form/>

        <div class="d-flex justify-content-center">
            <x-search-input/>
            @auth
                <a href="{{route('topic.create')}}" class="text-success my-4">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         width="25" height="25"
                         fill="currentColor"
                         class="bi bi-plus-circle"
                         viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                        <path
                            d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
                    </svg>
                </a>
            @endauth
        </div>

        <div class="d-flex flex-column mx-4">

            @foreach($allTopics as $topic)
                <x-topic-box :topic="$topic"/>
            @endforeach

        </div>

        @if(! $allTopics instanceof Collection)
            <div class="d-flex justify-content-center">
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                        <li class="page-item"><a class="page-link" href="{{$allTopics->previousPageUrl()}}">Previous</a>
                        </li>
                        <li class="page-item"><a class="page-link" href="{{$allTopics->nextPageUrl()}}">Next</a></li>
                    </ul>
                </nav>
            </div>
        @endif

    </div>


@endsection