Forensystem/routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\BoardController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\TopicController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

















// Public

Route::view('/','components.login-form')->name('loginPage');
Route::post('/login', [AuthController::class,'login'])->name('login');
Route::view('/registerForm','components.register')->name('registerForm');
Route::view('/resetPasswordForm','components.forget-password')->name('resetPasswordForm');
Route::post('/usersRegister',[AuthController::class,'register'])->name('register');
Route::post('/sendResetMail',[AuthController::class,'sendResetMail'])->name('reset.mail');
Route::post('/verifyResetCode',[AuthController::class,'verifyResetCode'])->name('verifyCode');
Route::post('/resetPassword',[AuthController::class,'resetPassword'])->name('reset.password');
Route::get('/getBoardTopics/{board}',[TopicController::class,'boardTopics'])->name('board.topics');
Route::post('/search',[TopicController::class,'search'])->name('search');
Route::view('getForgetPassword','components.forget-password')->name('test');


// Authentication
Route::middleware('auth')->group(function (){
    Route::resource('notification', NotificationController::class);
    Route::get('/notificationOp/{op}',[NotificationController::class,'readOrDelete'])->name('notification.options');

    Route::get('/getProfilePage',[AuthController::class,'getProfilePage'])->name('get.Account');
    Route::put('/editProfile',[AuthController::class,'editAccount'])->name('edit.Account');

    Route::get('logout',[AuthController::class,'logout'])->name('logout');

    Route::resource('comment',CommentController::class);
    Route::resource('topic', TopicController::class)->except('index','show');

    Route::middleware('can:isAdmin')->group(function (){
        Route::resource('board', BoardController::class);
        Route::resource('users', UsersController::class);
    });
});

Route::resource('topic', TopicController::class)->only('index','show');

Forensystem/resources/views/layout/main.blade.php
@php
    use Illuminate\Support\Facades\Auth;
    use Illuminate\Support\Facades\Session;

@endphp
    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <title>Gh-SO</title>
</head>
@vite(['resources/js/app.js'])

<nav class="navbar navbar-expand-lg bg-dark">
    <div class="container-fluid">
        @auth
            <a class="navbar-brand text-white me-5" href="{{route('get.Account')}}">
                @if(Auth::user()->profilePic == null)
                    <i class="bi bi-person-circle text-white fs-2"></i>
                @else
                    <img class="rounded-5" src="{{asset('storage/images/'.Auth::user()->profilePic)}}"
                         alt="Picture"
                         style="max-width: 45px; max-height:45px">
                @endif
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        @endauth

        @if(!Auth::check())
            <div>
                <a class="nav-link text-white" href="{{route('loginPage')}}">Login</a>
            </div>
        @endif

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav row-cols-lg-1">
                <li class="nav-item">
                    <a class="nav-link active text-white" aria-current="page" href="{{route('topic.index')}}">Home</a>
                </li>

                @auth
                    @can('isAdmin')
                        <li class="nav-item dropdown">
                            <a class="nav-link text-white" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                Management
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{route('users.index')}}">Users</a></li>
                                <li><a class="dropdown-item" href="{{route('board.index')}}">Boards</a></li>
                            </ul>
                        </li>
                    @endcan
                    <li class="nav-item dropdown">
                        <a class="nav-link text-white fs-5" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            <i class="bi bi-bell-fill position-relative">
                                @if(Session::get('unread') > 0)
                                    <div class="position-absolute translate-middle badge rounded-pill bg-danger">
                                        {{Session::get('unread')}}
                                    </div>
                                @endif
                            </i>
                        </a>

                        <ul class="dropdown-menu">
                            @if(Session::get('notification')->count() > 0)
                                <li>
                                    <div class="d-flex justify-content-around">
                                        <div>
                                            <a class="dropdown-item" href="{{route('notification.index')}}">
                                                <i class="bi bi-arrow-clockwise"></i>
                                            </a>
                                        </div>
                                        <div>
                                            <a class="dropdown-item" href="{{route('notification.options','+')}}">
                                                <i class="bi bi-check2-all"></i>
                                            </a>
                                        </div>
                                        <div>
                                            <a class="dropdown-item" href="{{route('notification.options','-')}}">
                                                <i class="bi bi-trash"></i>
                                            </a>
                                        </div>
                                    </div>
                                </li>
                            @else

                                <li>
                                    <p class="dropdown-item" >No Notifications</p>
                                </li>
                            @endif

                            @foreach( Session::get('notification') as $not )
                                <li>
                                    <div class="d-flex justify-content-between">
                                        @if(!$not->read)
                                            <a class="dropdown-item text-primary-emphasis" href="{{route('notification.show',$not->id)}}">
                                                {{$not->topic->board->name}}
                                            </a>
                                        @else
                                            <a class="dropdown-item" href="{{route('notification.show',$not->id)}}">
                                                {{$not->topic->board->name}}
                                            </a>
                                        @endif
                                        <div class="d-flex justify-content-between">
                                            <form class="mx-3" action="{{route('notification.destroy',$not->id)}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn">
                                                    <i class="bi bi-trash3 text-danger fs-5"></i>
                                                </button>
                                            </form>
                                            <a href="{{route('notification.edit',$not->id)}}"><i class="bi bi-check2-circle text-success fs-4 mx-2"></i></a>
                                        </div>
                                    </div>
                                </li>
                            @endforeach

                        </ul>
                    </li>
                    <li class="nav-item text-danger">
                        <a class="nav-link" href="{{route('logout')}}">
                            <i class="bi bi-box-arrow-right text-danger fs-5"></i>
                        </a>
                    </li>
            </ul>
            @endauth

        </div>
    </div>
</nav>
@section('body')
@show
</html>

Forensystem/resources/views/layout/sub.blade.php
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>Gh-SO</title>
</head>
@vite(['resources/js/app.js'])

@section('body')
@show

</html>